Imports System.Text
Imports System.Security.Cryptography

Public Class PasswordManager
    Dim xmlDataSet As System.Data.DataSet
    Dim APICall As callAPI = New callAPI

    Sub New()
        Try
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Create a new DataSet
    
        Catch ex As Exception
            MsgBox(ex.ToString())
        End Try

    End Sub

    Private Sub PasswordManager_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        xmlDataSet = New System.Data.DataSet("XML DataSet")
        ' Load the XML document to the DataSet
        xmlDataSet.ReadXml("XMLFile1.xml")
        ' This line of code is generated by Data Source Configuration Wizard
        GridControl1.DataSource = xmlDataSet.Tables("Passwords")
    End Sub

    Private Sub GridView1_Click(sender As Object, e As EventArgs) Handles GridView1.Click, GridControl1.Click

    End Sub

    Public Sub SaveNewPassword(WalletName As String, passphrase As String, code As String)
        '  Dim xmlDataSet As System.Data.DataSet
     
        xmlDataSet.Tables("Passwords").Rows.Add(WalletName, APICall.AES_Encrypt(passphrase, code))
        xmlDataSet.Tables("Passwords").AcceptChanges()
        xmlDataSet.WriteXml("XMLFile1.xml")
    End Sub
    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles BtnEncrypt.Click
        ' MsgBox(AES_Decrypt(TxtHashPass.Text, TxtCodeEncrypt.Text).ToString())
        Try
            If TxtCodeEncrypt.Text = "" Then
                MsgBox("no code specified decrypting with default encryption code")
                TxtCodeEncrypt.Text = "Burst"
            End If
            Clipboard.SetDataObject(APICall.AES_Decrypt(TxtHashPass.Text, TxtCodeEncrypt.Text).ToString())
            BurstWallet.ClipboardClearTimer.Start()
            If CEKeepCodeInMemory.Checked = False Then
                TxtCodeEncrypt.Text = ""
            End If
            Me.Hide()
        Catch ex As Exception
            MsgBox(ex.ToString())
        End Try

    End Sub
    
    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles BtnSave.Click
               SaveNewPassword(TXTWalletName2.Text, TxtPass.Text, TxtCode.Text)

        TXTWalletName2.Text = ""
        TxtPass.Text = ""

    End Sub

    Private Sub GridView1_RowClick(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowClickEventArgs) Handles GridView1.RowClick

        TXTWalletName.Text = GridView1.GetFocusedDataRow(0).ToString
        TxtHashPass.Text = GridView1.GetFocusedDataRow(1).ToString
    End Sub
End Class